In [5]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, BernoulliNB, CategoricalNB
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score

In [43]:
Data = load_iris(as_frame = True)

In [47]:
df = pd.DataFrame

AttributeError: isnull

In [10]:
x = Data.data
y = Data.target

In [11]:
x.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [12]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int32

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x,y,  test_size= 0.2, random_state = 0)

In [26]:
gaussian_nb = GaussianNB()
bernoulli_nb = BernoulliNB()
categorical_nb = CategoricalNB()


In [27]:
gaussian_nb.fit(x_train, y_train)
bernoulli_nb.fit(x_train, y_train)
categorical_nb.fit(x_train, y_train)

CategoricalNB()

In [28]:
gaussian_nb_pred = gaussian_nb.predict(x_test)
bernoulli_nb_pred = bernoulli_nb.predict(x_test)
categorical_nb_pred = categorical_nb.predict(x_test)

In [29]:
gaussian_nb_acc = accuracy_score(y_test, gaussian_nb_pred)
bernoulli_nb_acc = accuracy_score(y_test,bernoulli_nb_pred)
categorical_nb_acc = accuracy_score(y_test,categorical_nb_pred)

In [30]:
print ('Accuracy for Guassian' ,gaussian_nb_acc*100 ,'%\n' )
print ('Accuracy for Bernoulli' ,bernoulli_nb_acc*100 ,'%\n' )
print ('Accuracy for Categorical' ,categorical_nb_acc*100 ,'%' )

Accuracy for Guassian 96.66666666666667 %

Accuracy for Bernoulli 20.0 %

Accuracy for Categorical 93.33333333333333 %


In [31]:
print("Error_rate of Guassian is :", (1-gaussian_nb_acc)*100, "% \n")
print("Error_rate of Bernoulli is :", (1-bernoulli_nb_acc)*100, "% \n")
print("Error_rate of Categorical is :", (1-categorical_nb_acc)*100, "%\n")

Error_rate of Guassian is : 3.3333333333333326 % 

Error_rate of Bernoulli is : 80.0 % 

Error_rate of Categorical is : 6.666666666666665 %



In [35]:
print("Confusion 1 :\n", confusion_matrix(y_test, gaussian_nb_pred),"\n")
print("Confusion 2:\n", confusion_matrix(y_test,bernoulli_nb_pred ),"\n")
print("Confusion 3:\n", confusion_matrix(y_test,categorical_nb_pred ),"\n")

Confusion 1 :
 [[11  0  0]
 [ 0 13  0]
 [ 0  1  5]] 

Confusion 2:
 [[ 0  0 11]
 [ 0  0 13]
 [ 0  0  6]] 

Confusion 3:
 [[11  0  0]
 [ 0 13  0]
 [ 0  2  4]] 



In [40]:
df_pred1 = gaussian_nb_pred

In [41]:
df = pd.DataFrame(dict(observed = y_test, predicted = df_pred1))
df.head()

observed  predicted
114         2          2
62          1          1
33          0          0
107         2          2
7           0          0